import { ABAFormSessionData } from './types';

export const initialData: ABAFormSessionData = {
  setting: '',
  sessionEmphasis: [],
  participationLevel: 3, // Default to High (0-4)
  affectEngagement: 2, // Default to Moderate Engagement (0-4)
  strategies: [],
  promptReceptiveness: 3, // Default to Highly Effective (0-4)
  teachingTargets: [],
  behaviorSeverity: 0, // Default to None (0-4)
  behaviorTypes: [],
  additionalDetails: '',
};

export const OPTIONS = {
  SETTING: ["Home", "Clinic", "School", "Community"],
  SESSION_EMPHASIS: ["Skill Acquisition", "Behavior Reduction", "Pairing/Rapport Building", "Gen/Maint"],
  STRATEGIES: ["Antecedent Strategies", "FCT", "NET", "DTT", "Differential Reinforcement", "Token Economy", "Prompting", "Errorless Learning", "Chaining/TA", "Consequence Strategies"],
  TEACHING_TARGETS: [
    "Manding for items",
    "Manding for actions",
    "Manding for help",
    "Requesting missing items",
    "Requesting a break",
    "Requesting attention",
    "Requesting information",
    "Requesting termination",
    "Requesting peer attention",
    "Manding with adjectives",
    "Manding with prepositions",
    "Labeling objects",
    "Labeling colors",
    "Labeling shapes",
    "Labeling animals",
    "Labeling helpers",
    "Labeling actions",
    "Labeling body parts",
    "Labeling emotions",
    "Labeling prepositions",
    "Labeling parts",
    "Labeling clothing",
    "Labeling foods",
    "Labeling vehicles",
    "Labeling places",
    "Labeling sounds",
    "Labeling attributes",
    "Labeling feelings",
    "Labeling sizes",
    "Labeling possession",
    "Receptive objects",
    "Receptive colors",
    "Receptive shapes",
    "Receptive animals",
    "Receptive helpers",
    "Receptive actions",
    "Receptive body parts",
    "Receptive emotions",
    "Receptive prepositions",
    "Receptive by function",
    "Receptive by feature",
    "Receptive by class",
    "Receptive clothing",
    "Receptive foods",
    "Receptive vehicles",
    "Receptive letters",
    "Receptive numbers",
    "Receptive sizes",
    "One-step instructions",
    "Two-step instructions",
    "Conditional instructions",
    "Responding to name",
    "Understanding pronouns",
    "Understanding adverbs",
    "Song fill ins",
    "Word associations",
    "Personal information",
    "Animal sounds",
    "Naming categories",
    "Identifying opposites",
    "Describing functions",
    "Describing features",
    "Describing classes",
    "Helper duties",
    "Object locations",
    "Yes no questions",
    "Wh questions",
    "Conversational turn taking",
    "Gross motor imitation",
    "Fine motor imitation",
    "Object imitation",
    "Two step imitation",
    "Oral imitation",
    "Sound echoics",
    "Syllable echoics",
    "Word echoics",
    "Phrase echoics",
    "Peer imitation",
    "Matching objects",
    "Matching pictures",
    "Non identical matching",
    "Object picture matching",
    "Sorting by color",
    "Sorting by shape",
    "Sorting by category",
    "Sorting by size",
    "Puzzle completion",
    "Block duplication",
    "Continuing patterns",
    "Independent play",
    "Peer turn taking",
    "Cooperative play",
    "Pretend play",
    "Initiating play",
    "Peer responsiveness",
    "Reading expressions",
    "Reading sight words",
    "Counting objects",
    "Writing name",
    "Visual schedules"
  ],
  BEHAVIOR_TYPES: ["Aggression", "Elopement", "Loud Vocals", "Task Refusal", "Property Destruction", "Tantrum", "SIB", "Negative Vocals"],
};
